### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by krazar** [shenxn/ha-dyson-cloud#1]
Hello and thank your for your work, this is really promising.

I am having an issue while using this integration. It refuses to login with my credentials (which work with the official app and 
 worked with official ha integration as well).

To be sure, I created a new account and test the connection with the same effect.

The error is "Invalid authentication"

Would you know where it could come from ?
Thank you

**Comment by ripburger** [comment]
I am having the same problem, it's probably because Dyson now requires 2FA when logging in (email sent with the 2FA code).

**Comment by monsieurlatte** [comment]
Odd I just signed into my account via web and also via the app and it didnt ask me or force me to setup 2FA, I too am getting the error when trying to connect.  glad there is a new fork/project happening, hopefully this one will get working and stay up, so grateful for the work the dev(s) do on these kinds of projects.

**Comment by krazar** [comment]
Same here I didn't understand why it failed as the app didn't require  2FA.

Now, it's fixed.
1. update your app
2. sign out & login in your app
3. get credentials via the script  get_credentials.py from libdyson repository (updated recently https://github.com/shenxn/ha-dyson/issues/5#issuecomment-791887983)
4. connect via dyson-local integration ( I guess this dyson-cloud integration will be updated soon too)

**Comment by shenxn** [comment]
Version 0.4.0 should fix this. Note you should upgrade both `ha-dyson` and `ha-dyson-cloud` to avoid upstream library conflict.
